topic_list_tiles_topic_lists:
  type: list
  category: "Tile Layout"
  default: latest|new|unread|top|tag|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|activity-topics-mobile|activity-portfolio-mobile
  description:
    en: >
      <div class="desc"><br><br><h2>Tile Layout</h2> Control which lists display the richer tile view.</div>
      The lists that will be styled with tiles format. Can be one of latest|new|unread|top|tag|suggested|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|suggested-mobile|activity-topics-mobile|activity-portfolio-mobile
topic_list_tiles_categories:
  type: list
  category: "Tile Layout"
  list_type: category
  default: ""
  description:
    en: "The categories that will be styled with tiles format."
topic_list_tiles_tags:
  type: list
  category: "Tile Layout"
  list_type: tag
  default: ""
  description:
    en: "The tags that will be styled with tiles format."
topic_list_tiles_larger_featured_tiles:
  type: bool
  category: "Tile Layout"
  default: true
  description:
    en: "Make the tiles with featured tags larger"
topic_list_tiles_wide_format:
  type: bool
  category: "Tile Layout"
  default: false
  description:
    en: "Use wide format (places image on left instead of top) for tiles when list area is wide enough"

topic_list_grid_topic_lists:
  type: list
  category: "Grid Layout"
  default: ""
  description:
    en: >
      <div class="desc"><br><br><h2>Grid Layout</h2> Enable the uniform grid card view without Masonry.</div>
      The lists that will be styled with the grid layout. Can be one of latest|new|unread|top|tag|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|suggested-mobile|agenda-mobile|activity-topics-mobile|activity-portfolio-mobile
topic_list_grid_categories:
  type: list
  category: "Grid Layout"
  list_type: category
  default: ""
  description:
    en: "The categories that will be styled with the grid layout."
topic_list_grid_tags:
  type: list
  category: "Grid Layout"
  list_type: tag
  default: ""
  description:
    en: "The tags that will be styled with the grid layout."
topic_list_grid_image_height:
  type: integer
  category: "Grid Layout"
  default: 200
  description:
    en: "Height for grid layout preview images (pixels)."

topic_list_thumbnails_topic_lists:
  type: list
  category: "Thumbnails"
  default: latest|new|unread|top|tag|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|suggested-mobile|agenda-mobile|activity-topics-mobile|activity-portfolio-mobile
  description:
    en: >
      <div class="desc"><br><br><h2>Thumbnails</h2> Manage default images and sizing for list previews.</div>
      The lists that will include thumbnails. Can be one of latest|new|unread|top|tag|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|suggested-mobile|agenda-mobile|activity-topics-mobile|activity-portfolio-mobile
topic_list_thumbnails_categories:
  type: list
  category: "Thumbnails"
  list_type: category
  default: ""
  description:
    en: "The categories that will include thumbnails."
topic_list_thumbnails_tags:
  type: list
  category: "Thumbnails"
  list_type: tag
  default: ""
  description:
    en: "The categories that will include thumbnails."
topic_list_default_thumbnail:
  type: string
  category: "Thumbnails"
  default: ""
  description:
    en: "Image URL for default thumbnail if topic thumbnail is inaccessible."
topic_list_default_thumbnail_fallback:
  type: bool
  category: "Thumbnails"
  default: false
  description:
    en: "Use the default thumbnail when a topic has no previewed image."
topic_list_thumbnail_resolution_level:
  type: integer
  category: "Thumbnails"
  default: 3
  max: 6
  min: 0
  description:
    en: "Resolution level of thumbnail used in the Topic List: 0 is original, 1 is next highest, up to 6 lowest. Actual resolution will depend on number of thumbnails available for any one image. Experiment for best setting for your site, but 2 is recommended for Tiles"
topic_list_thumbnail_width:
  category: "Thumbnails"
  default: 150
  description:
    en: "Width of image that can be previewed."
topic_list_thumbnail_height:
  category: "Thumbnails"
  default: 100
  description:
    en: "Height of image that can be previewed."
topic_list_thumbnail_width_mobile:
  category: "Thumbnails"
  default: 50
  description:
    en: "Width of image that can be previewed on mobile."
topic_list_thumbnail_height_mobile:
  category: "Thumbnails"
  default: 60
  description:
    en: "Height of image that can be previewed on mobile."
topic_list_thumbnail_first_x_rows:
  type: integer
  category: "Thumbnails"
  default: 0
  description:
    en: "Show thumbnail only for first X rows. Enter 0 to show on all rows."

topic_list_excerpts_topic_lists:
  type: list
  category: "Excerpts"
  default: latest|new|unread|top|tag|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|suggested-mobile|agenda-mobile|activity-topics-mobile|activity-portfolio-mobile
  description:
    en: >
      <div class="desc"><br><br><h2>Excerpts</h2> Decide where topic list previews include body text.</div>
      The lists that will include excerpts. Can be one of latest|new|unread|top|tag|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|suggested-mobile|agenda-mobile|activity-topics-mobile|activity-portfolio-mobile
topic_list_excerpts_categories:
  type: list
  category: "Excerpts"
  list_type: category
  default: ""
  description:
    en: "The categories that will include excerpts."
topic_list_excerpts_tags:
  type: list
  category: "Excerpts"
  list_type: tag
  default: ""
  description:
    en: "The tags that will include excerpts."

topic_list_actions_topic_lists:
  type: list
  category: "Topic Actions"
  default: latest|new|unread|top|tag|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|suggested-mobile|agenda-mobile|activity-topics-mobile|activity-portfolio-mobile
  description:
    en: >
      <div class="desc"><br><br><h2>Topic Actions</h2> Toggle where quick actions appear in list previews.</div>
      The lists that will include actions. Can be one of latest|new|unread|top|tag|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tag-mobile|suggested-mobile|agenda-mobile|activity-topics-mobile|activity-portfolio-mobile
topic_list_actions_categories:
  type: list
  category: "Topic Actions"
  list_type: category
  default: ""
  description:
    en: "The categories that will include actions."
topic_list_actions_tags:
  type: list
  category: "Topic Actions"
  list_type: tag
  default: ""
  description:
    en: "The tags that will include actions."

topic_list_set_category_defaults:
  type: bool
  category: "General Display"
  default: false
  description:
    en: >
      <div class="desc"><br><br><h2>General Display</h2> Site-wide behaviours affecting every topic list.</div>
      Set site topic list display settings as defaults for category topic lists.
topic_list_dominant_color_background:
  type: enum
  category: "General Display"
  default: tiles only
  choices:
    - never
    - tiles only
    - always
  description:
    en: "Use dominant color for background of topic list items."
topic_list_show_like_on_current_users_posts:
  type: bool
  category: "General Display"
  default: true
  description:
    en: "Show an inactive like button in topic list items previewing a post created by the current user (non-default Discourse behavior)."

topic_list_portfolio:
  type: bool
  category: "User Portfolio"
  default: true
  description:
    en: >
      <div class="desc"><br><br><h2>User Portfolio</h2> Configure the optional portfolio activity view.</div>
      Enable additional User Activity view for User Portfolio
topic_list_portfolio_icons:
  category: "User Portfolio"
  default: 'images'
  description:
    en: "The icon you wish to use for the Portfolio button and Portfolio label"
topic_list_portfolio_filter_type:
  type: enum
  category: "User Portfolio"
  default: "tag"
  choices:
    - tag
    - category
  description:
    en: "Which type of filter should be used to limit Activity Portfolio Topics"
topic_list_portfolio_filter_parameter:
  type: string
  category: "User Portfolio"
  default: ""
  description:
    en: "Enter the tag or category slug (depending of value of filter type setting)"

topic_list_featured_images:
  type: bool
  category: "Featured Images"
  default: false
  description:
    en: >
      <div class="desc"><br><br><h2>Featured Images</h2> Manage the hero-style featured topics banner.</div>
      Enable featured images for non-category routes.
topic_list_featured_images_resolution_level:
  type: integer
  category: "Featured Images"
  default: 2
  max: 6
  min: 0
  description:
    en: "Resolution level of thumbnail used in Featured Images: 0 is original, 1 is next highest, up to 6 lowest. Actual resolution will depend on number of thumbnails available for any one image. Experiment for best setting for your site."
topic_list_featured_images_category:
  type: bool
  category: "Featured Images"
  default: false
  description:
    en: "Apply featured images site setting to all category discovery routes"
topic_list_featured_images_from_current_category_only:
  type: bool
  category: "Featured Images"
  default: true
  description:
    en: "Show featured images only that exist in current Category"
topic_list_featured_images_tag:
  type: list
  category: "Featured Images"
  list_type: tag
  default: ""
  description:
    en: "Featured images tag."
topic_list_featured_images_tag_show:
  type: bool
  category: "Featured Images"
  default: true
  description:
    en: "Show featured images tag below featured images."
topic_list_featured_images_count:
  category: "Featured Images"
  default: 0
  description:
    en: "Featured Images Topics set count. Set to zero for no limit. NB If featured Topics don't contain a thumbnail the number of images will be fewer, just raise the number."
topic_list_featured_images_order:
  type: enum
  category: "Featured Images"
  default: latest
  choices:
    - latest
    - created
    - random
  description:
    en: "Featured Images order"
topic_list_featured_width:
  type: integer
  category: "Featured Images"
  default: 0
  description:
    en: "Featured image width.  Setting this to zero will make it responsive to image aspect ratio."
topic_list_featured_height:
  type: integer
  category: "Featured Images"
  default: 250
  description:
    en: "Featured image height."
topic_list_featured_height_mobile:
  type: integer
  category: "Featured Images"
  default: 150
  description:
    en: "Featured image height on mobile."
topic_list_featured_title:
  type: string
  category: "Featured Images"
  default: ""
  description:
    en: "Featured images title. Supports Markdown."
topic_list_featured_excerpt:
  type: integer
  category: "Featured Images"
  default: 100
  description:
    en: "Include topic excerpt in featured image and determine its length.  Set it to 0 for don't include"
topic_list_featured_details_always_show:
  type: enum
  category: "Featured Images"
  default: only on hover
  choices:
    - only on hover
    - mobile device
    - always
  description:
    en: "Always show details in featured image"

topic_list_fps_search_grid:
  type: bool
  category: "Full Page Search"
  default: true
  description:
    en: >
      <div class="desc"><br><br><h2>Full Page Search</h2> Customise the search results layout enhancements.</div>
      Enable search grid for full page search
topic_list_fps_search_blurb:
  type: bool
  category: "Full Page Search"
  default: true
  description:
    en: "Enable search blurb for full page search"
topic_list_fps_search_author:
  type: bool
  category: "Full Page Search"
  default: true
  description:
    en: "Enable search author for full page search"

topic_list_test_image_url_timeout:
  type: integer
  category: "Advanced"
  default: 5000
  description:
    en: >
      <div class="desc"><br><br><h2>Advanced</h2> Low-level tuning for edge cases and debugging.</div>
      Timeout for testing image url
